memory:
  start: 0x0000
  size: 0x1000

generation:
  iterations: 1

program:
  length: 100
  max_steps: 1000

execution:
  python_model: "golden_model.run"
  cpp_model: "./../build/src/riscv-emulator"

output:
  temp_dir: "temp"
  failure_dir: "failures"
